// <auto-generated />
using System;
using ApologiaStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApologiaStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApologiaStudioDbContext))]
    [Migration("20260803192559_AddRecoverableConversationDeletion")]
    partial class AddRecoverableConversationDeletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApologiaStudio.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("OwnerId", "DeletedAt", "ProjectId", "SortOrder", "CreatedAt")
                        .HasDatabaseName("ix_conversations_owner_project_sort_order");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Conversations.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_messages_conversation_created_at");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Navigation.SidebarPin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("target_kind");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("OwnerId", "ConversationId")
                        .IsUnique()
                        .HasDatabaseName("ux_sidebar_pins_owner_conversation")
                        .HasFilter("conversation_id IS NOT NULL");

                    b.HasIndex("OwnerId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_sidebar_pins_owner_project")
                        .HasFilter("project_id IS NOT NULL");

                    b.HasIndex("OwnerId", "SortOrder", "CreatedAt")
                        .HasDatabaseName("ix_sidebar_pins_owner_sort_order");

                    b.ToTable("sidebar_pins", null, t =>
                        {
                            t.HasCheckConstraint("ck_sidebar_pins_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_sidebar_pins_target", "(target_kind = 'Conversation' AND conversation_id IS NOT NULL AND project_id IS NULL) OR (target_kind = 'Project' AND project_id IS NOT NULL AND conversation_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Projects.ConversationProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_projects_owner_name");

                    b.HasIndex("OwnerId", "SortOrder", "CreatedAt")
                        .HasDatabaseName("ix_conversation_projects_owner_sort_order");

                    b.ToTable("conversation_projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversation_projects_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Users.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("InterfaceLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("interface_language");

                    b.Property<string>("TheologicalLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("theological_language");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_preferences_interface_language", "interface_language IN ('French', 'English')");

                            t.HasCheckConstraint("ck_user_preferences_theological_language", "theological_language IS NULL OR theological_language IN ('French', 'English')");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleBookEntity", b =>
                {
                    b.Property<string>("UsfmCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("usfm_code");

                    b.Property<string>("CanonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("canon_code");

                    b.Property<int>("CanonicalOrder")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_order");

                    b.Property<string>("OsisCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("osis_code");

                    b.HasKey("UsfmCode");

                    b.HasIndex("CanonicalOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_books_canonical_order");

                    b.HasIndex("OsisCode")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_books_osis_code");

                    b.ToTable("bible_books", null, t =>
                        {
                            t.HasCheckConstraint("ck_bible_books_canonical_order_positive", "canonical_order > 0");
                        });

                    b.HasData(
                        new
                        {
                            UsfmCode = "GEN",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 1,
                            OsisCode = "Gen"
                        },
                        new
                        {
                            UsfmCode = "EXO",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 2,
                            OsisCode = "Exod"
                        },
                        new
                        {
                            UsfmCode = "LEV",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 3,
                            OsisCode = "Lev"
                        },
                        new
                        {
                            UsfmCode = "NUM",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 4,
                            OsisCode = "Num"
                        },
                        new
                        {
                            UsfmCode = "DEU",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 5,
                            OsisCode = "Deut"
                        },
                        new
                        {
                            UsfmCode = "JOS",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 6,
                            OsisCode = "Josh"
                        },
                        new
                        {
                            UsfmCode = "JDG",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 7,
                            OsisCode = "Judg"
                        },
                        new
                        {
                            UsfmCode = "RUT",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 8,
                            OsisCode = "Ruth"
                        },
                        new
                        {
                            UsfmCode = "1SA",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 9,
                            OsisCode = "1Sam"
                        },
                        new
                        {
                            UsfmCode = "2SA",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 10,
                            OsisCode = "2Sam"
                        },
                        new
                        {
                            UsfmCode = "1KI",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 11,
                            OsisCode = "1Kgs"
                        },
                        new
                        {
                            UsfmCode = "2KI",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 12,
                            OsisCode = "2Kgs"
                        },
                        new
                        {
                            UsfmCode = "1CH",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 13,
                            OsisCode = "1Chr"
                        },
                        new
                        {
                            UsfmCode = "2CH",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 14,
                            OsisCode = "2Chr"
                        },
                        new
                        {
                            UsfmCode = "EZR",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 15,
                            OsisCode = "Ezra"
                        },
                        new
                        {
                            UsfmCode = "NEH",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 16,
                            OsisCode = "Neh"
                        },
                        new
                        {
                            UsfmCode = "EST",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 17,
                            OsisCode = "Esth"
                        },
                        new
                        {
                            UsfmCode = "JOB",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 18,
                            OsisCode = "Job"
                        },
                        new
                        {
                            UsfmCode = "PSA",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 19,
                            OsisCode = "Ps"
                        },
                        new
                        {
                            UsfmCode = "PRO",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 20,
                            OsisCode = "Prov"
                        },
                        new
                        {
                            UsfmCode = "ECC",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 21,
                            OsisCode = "Eccl"
                        },
                        new
                        {
                            UsfmCode = "SNG",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 22,
                            OsisCode = "Song"
                        },
                        new
                        {
                            UsfmCode = "ISA",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 23,
                            OsisCode = "Isa"
                        },
                        new
                        {
                            UsfmCode = "JER",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 24,
                            OsisCode = "Jer"
                        },
                        new
                        {
                            UsfmCode = "LAM",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 25,
                            OsisCode = "Lam"
                        },
                        new
                        {
                            UsfmCode = "EZK",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 26,
                            OsisCode = "Ezek"
                        },
                        new
                        {
                            UsfmCode = "DAN",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 27,
                            OsisCode = "Dan"
                        },
                        new
                        {
                            UsfmCode = "HOS",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 28,
                            OsisCode = "Hos"
                        },
                        new
                        {
                            UsfmCode = "JOL",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 29,
                            OsisCode = "Joel"
                        },
                        new
                        {
                            UsfmCode = "AMO",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 30,
                            OsisCode = "Amos"
                        },
                        new
                        {
                            UsfmCode = "OBA",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 31,
                            OsisCode = "Obad"
                        },
                        new
                        {
                            UsfmCode = "JON",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 32,
                            OsisCode = "Jonah"
                        },
                        new
                        {
                            UsfmCode = "MIC",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 33,
                            OsisCode = "Mic"
                        },
                        new
                        {
                            UsfmCode = "NAM",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 34,
                            OsisCode = "Nah"
                        },
                        new
                        {
                            UsfmCode = "HAB",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 35,
                            OsisCode = "Hab"
                        },
                        new
                        {
                            UsfmCode = "ZEP",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 36,
                            OsisCode = "Zeph"
                        },
                        new
                        {
                            UsfmCode = "HAG",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 37,
                            OsisCode = "Hag"
                        },
                        new
                        {
                            UsfmCode = "ZEC",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 38,
                            OsisCode = "Zech"
                        },
                        new
                        {
                            UsfmCode = "MAL",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 39,
                            OsisCode = "Mal"
                        },
                        new
                        {
                            UsfmCode = "MAT",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 40,
                            OsisCode = "Matt"
                        },
                        new
                        {
                            UsfmCode = "MRK",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 41,
                            OsisCode = "Mark"
                        },
                        new
                        {
                            UsfmCode = "LUK",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 42,
                            OsisCode = "Luke"
                        },
                        new
                        {
                            UsfmCode = "JHN",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 43,
                            OsisCode = "John"
                        },
                        new
                        {
                            UsfmCode = "ACT",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 44,
                            OsisCode = "Acts"
                        },
                        new
                        {
                            UsfmCode = "ROM",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 45,
                            OsisCode = "Rom"
                        },
                        new
                        {
                            UsfmCode = "1CO",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 46,
                            OsisCode = "1Cor"
                        },
                        new
                        {
                            UsfmCode = "2CO",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 47,
                            OsisCode = "2Cor"
                        },
                        new
                        {
                            UsfmCode = "GAL",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 48,
                            OsisCode = "Gal"
                        },
                        new
                        {
                            UsfmCode = "EPH",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 49,
                            OsisCode = "Eph"
                        },
                        new
                        {
                            UsfmCode = "PHP",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 50,
                            OsisCode = "Phil"
                        },
                        new
                        {
                            UsfmCode = "COL",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 51,
                            OsisCode = "Col"
                        },
                        new
                        {
                            UsfmCode = "1TH",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 52,
                            OsisCode = "1Thess"
                        },
                        new
                        {
                            UsfmCode = "2TH",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 53,
                            OsisCode = "2Thess"
                        },
                        new
                        {
                            UsfmCode = "1TI",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 54,
                            OsisCode = "1Tim"
                        },
                        new
                        {
                            UsfmCode = "2TI",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 55,
                            OsisCode = "2Tim"
                        },
                        new
                        {
                            UsfmCode = "TIT",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 56,
                            OsisCode = "Titus"
                        },
                        new
                        {
                            UsfmCode = "PHM",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 57,
                            OsisCode = "Phlm"
                        },
                        new
                        {
                            UsfmCode = "HEB",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 58,
                            OsisCode = "Heb"
                        },
                        new
                        {
                            UsfmCode = "JAS",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 59,
                            OsisCode = "Jas"
                        },
                        new
                        {
                            UsfmCode = "1PE",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 60,
                            OsisCode = "1Pet"
                        },
                        new
                        {
                            UsfmCode = "2PE",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 61,
                            OsisCode = "2Pet"
                        },
                        new
                        {
                            UsfmCode = "1JN",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 62,
                            OsisCode = "1John"
                        },
                        new
                        {
                            UsfmCode = "2JN",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 63,
                            OsisCode = "2John"
                        },
                        new
                        {
                            UsfmCode = "3JN",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 64,
                            OsisCode = "3John"
                        },
                        new
                        {
                            UsfmCode = "JUD",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 65,
                            OsisCode = "Jude"
                        },
                        new
                        {
                            UsfmCode = "REV",
                            CanonCode = "protestant-66",
                            CanonicalOrder = 66,
                            OsisCode = "Rev"
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleCorpusBookEntity", b =>
                {
                    b.Property<Guid>("CorpusVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("corpus_version_id");

                    b.Property<string>("UsfmBookCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("usfm_book_code");

                    b.Property<int>("BookOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("book_ordinal");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name");

                    b.Property<string>("SourceRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_relative_path");

                    b.HasKey("CorpusVersionId", "UsfmBookCode");

                    b.HasIndex("UsfmBookCode");

                    b.HasIndex("CorpusVersionId", "BookOrdinal")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_corpus_books_version_ordinal");

                    b.ToTable("bible_corpus_books", null, t =>
                        {
                            t.HasCheckConstraint("ck_bible_corpus_books_book_ordinal_positive", "book_ordinal > 0");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleCorpusVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int>("CanonicalSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_schema_version");

                    b.Property<string>("EditionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("edition_code");

                    b.Property<string>("ImportFingerprint")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("import_fingerprint");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizationPolicyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalization_policy_id");

                    b.Property<string>("ParserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parser_name");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("parser_version");

                    b.Property<string>("SourceTreeSha256")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("source_tree_sha256");

                    b.Property<string>("UpstreamRevision")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("upstream_revision");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("EditionCode")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_corpus_versions_active_edition")
                        .HasFilter("is_active");

                    b.HasIndex("ImportFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_corpus_versions_import_fingerprint");

                    b.HasIndex("EditionCode", "ImportedAt")
                        .HasDatabaseName("ix_bible_corpus_versions_edition_imported_at");

                    b.ToTable("bible_corpus_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_bible_corpus_versions_approval", "(approved_at IS NULL OR approved_at >= imported_at) AND (NOT is_active OR (approved_at IS NOT NULL AND validation_status = 'approved'))");

                            t.HasCheckConstraint("ck_bible_corpus_versions_import_fingerprint", "import_fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_bible_corpus_versions_schema_version_positive", "canonical_schema_version > 0");

                            t.HasCheckConstraint("ck_bible_corpus_versions_source_tree_sha256", "source_tree_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_bible_corpus_versions_validation_status", "validation_status IN ('pending', 'validated', 'approved', 'failed')");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleEditionEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("CanonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("canon_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language_tag");

                    b.HasKey("Code");

                    b.ToTable("bible_editions", (string)null);
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleSourceArtifactEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<Guid>("CorpusVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("corpus_version_id");

                    b.Property<DateTimeOffset>("DownloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloaded_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_uri");

                    b.HasKey("Id");

                    b.HasIndex("CorpusVersionId", "Role", "FileName")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_source_artifacts_version_role_file");

                    b.ToTable("bible_source_artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_bible_source_artifacts_byte_length_positive", "byte_length > 0");

                            t.HasCheckConstraint("ck_bible_source_artifacts_role", "role IN ('canonical-usfm', 'validation-vpl', 'validation-report')");

                            t.HasCheckConstraint("ck_bible_source_artifacts_sha256", "sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleSupplementalTextEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CharacterOffset")
                        .HasColumnType("integer")
                        .HasColumnName("character_offset");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("marker");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("placement");

                    b.Property<int>("SourceOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("source_ordinal");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("VerseId")
                        .HasColumnType("bigint")
                        .HasColumnName("verse_id");

                    b.HasKey("Id");

                    b.HasIndex("VerseId", "SourceOrdinal")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_supplemental_texts_verse_ordinal");

                    b.ToTable("bible_supplemental_texts", null, t =>
                        {
                            t.HasCheckConstraint("ck_bible_supplemental_texts_marker", "marker IN ('d', 'sp')");

                            t.HasCheckConstraint("ck_bible_supplemental_texts_offset", "(placement = 'Within' AND character_offset >= 0) OR (placement IN ('Before', 'After') AND character_offset IS NULL)");

                            t.HasCheckConstraint("ck_bible_supplemental_texts_ordinal_positive", "source_ordinal > 0");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleVerseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.Property<Guid>("CorpusVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("corpus_version_id");

                    b.Property<int>("SourceLine")
                        .HasColumnType("integer")
                        .HasColumnName("source_line");

                    b.Property<string>("SourceRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_relative_path");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("UsfmBookCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("usfm_book_code");

                    b.Property<string>("VerseLabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verse_label");

                    b.Property<int>("VerseOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("verse_ordinal");

                    b.HasKey("Id");

                    b.HasIndex("CorpusVersionId", "UsfmBookCode", "ChapterNumber", "VerseLabel")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_verses_reference");

                    b.HasIndex("CorpusVersionId", "UsfmBookCode", "ChapterNumber", "VerseOrdinal")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_verses_order");

                    b.ToTable("bible_verses", null, t =>
                        {
                            t.HasCheckConstraint("ck_bible_verses_chapter_positive", "chapter_number > 0");

                            t.HasCheckConstraint("ck_bible_verses_ordinal_positive", "verse_ordinal > 0");

                            t.HasCheckConstraint("ck_bible_verses_source_line_positive", "source_line > 0");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleWordAnnotationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attribute_name");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attribute_value");

                    b.Property<int>("CharacterLength")
                        .HasColumnType("integer")
                        .HasColumnName("character_length");

                    b.Property<int>("CharacterOffset")
                        .HasColumnType("integer")
                        .HasColumnName("character_offset");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("marker");

                    b.Property<int>("SourceOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("source_ordinal");

                    b.Property<long>("VerseId")
                        .HasColumnType("bigint")
                        .HasColumnName("verse_id");

                    b.HasKey("Id");

                    b.HasIndex("VerseId", "SourceOrdinal")
                        .IsUnique()
                        .HasDatabaseName("ux_bible_word_annotations_verse_ordinal");

                    b.ToTable("bible_word_annotations", null, t =>
                        {
                            t.HasCheckConstraint("ck_bible_word_annotations_length_positive", "character_length > 0");

                            t.HasCheckConstraint("ck_bible_word_annotations_offset_nonnegative", "character_offset >= 0");

                            t.HasCheckConstraint("ck_bible_word_annotations_ordinal_positive", "source_ordinal > 0");
                        });
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Conversations.Conversation", b =>
                {
                    b.HasOne("ApologiaStudio.Domain.Projects.ConversationProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Conversations.ConversationMessage", b =>
                {
                    b.HasOne("ApologiaStudio.Domain.Conversations.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Navigation.SidebarPin", b =>
                {
                    b.HasOne("ApologiaStudio.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApologiaStudio.Domain.Projects.ConversationProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleCorpusBookEntity", b =>
                {
                    b.HasOne("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleCorpusVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("CorpusVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleBookEntity", null)
                        .WithMany()
                        .HasForeignKey("UsfmBookCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleCorpusVersionEntity", b =>
                {
                    b.HasOne("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleEditionEntity", null)
                        .WithMany()
                        .HasForeignKey("EditionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleSourceArtifactEntity", b =>
                {
                    b.HasOne("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleCorpusVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("CorpusVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleSupplementalTextEntity", b =>
                {
                    b.HasOne("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleVerseEntity", null)
                        .WithMany()
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleVerseEntity", b =>
                {
                    b.HasOne("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleCorpusBookEntity", null)
                        .WithMany()
                        .HasForeignKey("CorpusVersionId", "UsfmBookCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleWordAnnotationEntity", b =>
                {
                    b.HasOne("ApologiaStudio.Infrastructure.Persistence.BibleCorpora.BibleVerseEntity", null)
                        .WithMany()
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApologiaStudio.Domain.Conversations.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
